const aisMessageMapping = {
  "1": "Scheduled position report (Class A)",
  "2": "Assigned scheduled position report (Class A)",
  "3": "Special position report, response to interrogation (Class A)",
  "4": "Position, UTC, date, and slot number of base station",
  "5": "Static and voyage related data (Class A)",
  "6": "Binary addressed message",
  "7": "Binary acknowledgement",
  "8": "Binary broadcast message",
  "9": "SAR aircraft position report",
  "10": "UTC/date inquiry",
  "11": "UTC/date response",
  "12": "Addressed safety related message",
  "13": "Safety related acknowledgement",
  "14": "Safety related broadcast message",
  "15": "Interrogation",
  "16": "Assignment mode command",
  "17": "DGNSS broadcast binary message",
  "18": "Standard Class B position report",
  "19": "Extended Class B position report",
  "20": "Data link management message",
  "21": "Aids-to-navigation report",
  "22": "Channel management",
  "23": "Group assignment command",
  "24": "Static data report",
  "25": "Single-slot binary message",
  "26": "Multiple-slot binary message",
  "27": "Position report for long-range applications"
};
